### ISSUE TITLE
MP-BGP

### ISSUE THREAD

**Issue by natesales** [natesales/bcg#18]
Let's add support for multiprotocol BGP sessions (IPv4 unicast and IPv6 unicast MP_REACH_NLRI). Something like this may work:

```yaml
asn: 34553
type: peer
mp-neighbors:
  - "192.0.2.1"
  - "2001:db8::2"
```
